services:
  filestore:
    build:
      context: .
      dockerfile: FileStoreService/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - filestore_data:/app/Files

  analysis:
    build:
      context: .
      dockerfile: FileAnalysisService/Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - filestore_data:/app/Files
    depends_on:
      - filestore

  gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - filestore
      - analysis

volumes:
  filestore_data:
